services:
  backend:
    build: .
    container_name: expert_rating_backend_prod
    restart: always
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    entrypoint: /usr/local/bin/docker-entrypoint-backend.sh
    env_file: .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - logs_data_prod:/app/logs
    depends_on:
      - redis

  nocodb:
      image: nocodb/nocodb:latest
      container_name: expert_rating_nocodb
      restart: always
      environment:
        NC_DB: "mysql2://91.236.136.58:3306?u=meguro_expvk&p=jE7pD9uH3w&d=meguro_expratingvk"
        NC_PUBLIC_URL: "http://db.api.exprating.ru/"
      ports:
        - "127.0.0.1:8080:8080"

  redis:
    image: redis:7-alpine
    container_name: expert_rating_redis_prod
    restart: always
    volumes:
      - redis_data_prod:/data

  loki:
    image: grafana/loki:2.9.0
    container_name: expert_rating_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.0
    container_name: expert_rating_promtail
    volumes:
      - ./logs:/var/log/app_logs
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: expert_rating_grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - loki
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

    
volumes:
  redis_data_prod:
  logs_data_prod:
  loki_data:
  grafana_data: