services:
  backend:
    build: .
    container_name: expert_rating_backend_prod
    restart: always
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    entrypoint: /usr/local/bin/docker-entrypoint-backend.sh
    env_file: .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - logs_data_prod:/app/logs
    depends_on:
      - redis

  nocodb:
      image: nocodb/nocodb:latest
      container_name: expert_rating_nocodb
      restart: always
      environment:
        NC_DB: "mysql2://expert_rating_mysql_dev:3306?u=devuser&p=devpass&d=expert_rating_dev"
      ports:
        - "8080:8080"
      depends_on:
        - db

  redis:
    image: redis:7-alpine
    container_name: expert_rating_redis_prod
    restart: always
    volumes:
      - redis_data_prod:/data

volumes:
  redis_data_prod:
  logs_data_prod: