"""Create initial tables

Revision ID: 3e945d22519c
Revises: 
Create Date: 2025-09-30 19:23:10.415842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e945d22519c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_expert', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('vk_id')
    )
    op.create_table('ExpertProfiles',
    sa.Column('user_vk_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected'), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('social_link', sa.Text(), nullable=True),
    sa.Column('regalia', sa.Text(), nullable=True),
    sa.Column('performance_link', sa.Text(), nullable=True),
    sa.Column('referrer_info', sa.Text(), nullable=True),
    sa.Column('tariff_plan', sa.String(length=50), nullable=True),
    sa.Column('tariff_expiry_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('show_contacts_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_vk_id'], ['Users.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_vk_id')
    )
    op.create_table('Events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expert_id', sa.BigInteger(), nullable=True),
    sa.Column('promo_word', sa.String(length=100), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected'), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('show_contacts', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['ExpertProfiles.user_vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_word')
    )
    op.create_table('ExpertTopics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expert_id', sa.BigInteger(), nullable=True),
    sa.Column('topic_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['ExpertProfiles.user_vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voter_vk_id', sa.BigInteger(), nullable=True),
    sa.Column('expert_vk_id', sa.BigInteger(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('vote_type', sa.Enum('trust', 'distrust'), nullable=True),
    sa.Column('comment_positive', sa.Text(), nullable=True),
    sa.Column('comment_negative', sa.Text(), nullable=True),
    sa.Column('is_expert_vote', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['Events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expert_vk_id'], ['ExpertProfiles.user_vk_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_vk_id'], ['Users.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Votes')
    op.drop_table('ExpertTopics')
    op.drop_table('Events')
    op.drop_table('ExpertProfiles')
    op.drop_table('Users')
    # ### end Alembic commands ###
