"""create_mailings_table

Revision ID: 136af79a7d96
Revises: 2dd95c0acec4
Create Date: 2025-10-23 12:05:31.502089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "136af79a7d96"
down_revision: Union[str, Sequence[str], None] = "2dd95c0acec4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Mailings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("expert_vk_id", sa.BigInteger(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Enum("pending", "approved", "rejected", "sent"), nullable=False
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("processed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["expert_vk_id"], ["ExpertProfiles.user_vk_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("Votes", "comment_neutral")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Votes", sa.Column("comment_neutral", mysql.TEXT(), nullable=True))
    op.drop_table("Mailings")
    # ### end Alembic commands ###
