"""Add event_date to Event model

Revision ID: 13e4342c131f
Revises: 3e945d22519c
Create Date: 2025-10-04 11:00:08.092957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13e4342c131f"
down_revision: Union[str, Sequence[str], None] = "3e945d22519c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Events", sa.Column("event_date", sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Events", "event_date")
    # ### end Alembic commands ###
