"""tariff table

Revision ID: 161fd223c572
Revises: 174fa35c84eb
Create Date: 2026-02-12 19:22:55.877625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161fd223c572'
down_revision: Union[str, Sequence[str], None] = '174fa35c84eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_votes', sa.Integer(), nullable=True),
    sa.Column('vk_donut_link', sa.Text(), nullable=True),
    sa.Column('event_limit', sa.Integer(), nullable=True),
    sa.Column('event_duration_hours', sa.Integer(), nullable=True),
    sa.Column('max_votes_per_event', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_code'), 'tariffs', ['code'], unique=True)
    op.create_unique_constraint('uq_expert_voter_rating_type', 'expert_ratings', ['expert_id', 'voter_id', 'rating_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_expert_voter_rating_type', 'expert_ratings', type_='unique')
    op.drop_index(op.f('ix_tariffs_code'), table_name='tariffs')
    op.drop_table('tariffs')
    # ### end Alembic commands ###
