"""Add_rating_type_to_social

Revision ID: 174fa35c84eb
Revises: 179f5f433913
Create Date: 2026-01-26 14:58:07.593563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "174fa35c84eb"
down_revision: Union[str, Sequence[str], None] = "179f5f433913"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expert_ratings", sa.Column("rating_type", sa.String(length=20), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expert_ratings", "rating_type")
    # ### end Alembic commands ###
