"""add_thank_you_message_and_reminder_to_events

Revision ID: 2358828315db
Revises: 62d609be4cce
Create Date: 2025-10-20 13:42:00.404627

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "2358828315db"
down_revision: Union[str, Sequence[str], None] = "62d609be4cce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Events", sa.Column("voter_thank_you_message", sa.Text(), nullable=True)
    )
    op.add_column(
        "Events",
        sa.Column("send_reminder", sa.Boolean(), server_default="0", nullable=False),
    )
    op.alter_column(
        "Events",
        "event_name",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.String(length=128),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Events",
        "event_name",
        existing_type=sa.String(length=128),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("Events", "send_reminder")
    op.drop_column("Events", "voter_thank_you_message")
    # ### end Alembic commands ###
