"""New

Revision ID: 5516e0bdcbe9
Revises: d2fe54f7ba15
Create Date: 2025-10-05 23:38:06.034137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5516e0bdcbe9'
down_revision: Union[str, Sequence[str], None] = 'd2fe54f7ba15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('event_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Events', 'event_link')
    # ### end Alembic commands ###
