"""add_timezone_to_datetime_columns

Revision ID: 5b1004f3fedf
Revises: 1ac59f76c6dd
Create Date: 2025-10-09 15:20:03.229786

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "5b1004f3fedf"
down_revision: Union[str, Sequence[str], None] = "1ac59f76c6dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
