"""add_neutral_vote_status_and_comment

Revision ID: 62d609be4cce
Revises: 5a8ffc1a3979
Create Date: 2025-10-20 09:56:50.336536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62d609be4cce"
down_revision: Union[str, Sequence[str], None] = "5a8ffc1a3979"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Votes", sa.Column("comment_neutral", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Votes", "comment_neutral")
    # ### end Alembic commands ###
