"""add_reminder_sent

Revision ID: 639e282a96d8
Revises: 136af79a7d96
Create Date: 2025-10-23 16:38:19.595915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "639e282a96d8"
down_revision: Union[str, Sequence[str], None] = "136af79a7d96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Events",
        sa.Column("reminder_sent", sa.Boolean(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Events", "reminder_sent")
    # ### end Alembic commands ###
