"""add activation limits and tracking to promo codes and add notification settings to user model

Revision ID: 8cd7172669ff
Revises: df1ff8ba1dd8
Create Date: 2025-10-21 14:00:08.368979

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cd7172669ff"
down_revision: Union[str, Sequence[str], None] = "df1ff8ba1dd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "PromoCodeActivations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("promo_code_id", sa.Integer(), nullable=False),
        sa.Column("user_vk_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "activated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["promo_code_id"], ["PromoCodes.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_vk_id"], ["Users.vk_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "PromoCodes", sa.Column("activations_limit", sa.Integer(), nullable=True)
    )
    op.add_column(
        "PromoCodes", sa.Column("user_activations_limit", sa.Integer(), nullable=False)
    )
    op.add_column(
        "Users",
        sa.Column(
            "allow_notifications", sa.Boolean(), server_default="1", nullable=False
        ),
    )
    op.add_column(
        "Users",
        sa.Column(
            "allow_expert_mailings", sa.Boolean(), server_default="1", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Users", "allow_expert_mailings")
    op.drop_column("Users", "allow_notifications")
    op.drop_column("PromoCodes", "user_activations_limit")
    op.drop_column("PromoCodes", "activations_limit")
    op.drop_table("PromoCodeActivations")
    # ### end Alembic commands ###
