"""add_unique_constraints_to_votes

Revision ID: 9ba024e2434f
Revises: c3272b570708
Create Date: 2025-12-16 18:57:08.054773

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9ba024e2434f"
down_revision: Union[str, Sequence[str], None] = "c3272b570708"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_voter_community_vote",
        "Votes",
        ["voter_vk_id", "expert_vk_id", "is_expert_vote"],
    )
    op.create_unique_constraint(
        "uq_voter_event_vote", "Votes", ["voter_vk_id", "event_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_voter_event_vote", "Votes", type_="unique")
    op.drop_constraint("uq_voter_community_vote", "Votes", type_="unique")
    # ### end Alembic commands ###
