"""add_email_to_user_model

Revision ID: a3e3adbcc7e2
Revises: 639e282a96d8
Create Date: 2025-11-02 19:30:23.043414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3e3adbcc7e2"
down_revision: Union[str, Sequence[str], None] = "639e282a96d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Users", sa.Column("email", sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, "Users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Users", type_="unique")
    op.drop_column("Users", "email")
    # ### end Alembic commands ###
