"""add forced_tariff_id

Revision ID: ad4b1c2d3e4f
Revises: 161fd223c572
Create Date: 2026-02-17 19:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4b1c2d3e4f'
down_revision: Union[str, Sequence[str], None] = '161fd223c572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('forced_tariff_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'tariffs', ['forced_tariff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'forced_tariff_id')
    # ### end Alembic commands ###
