"""create_expert_update_requests

Revision ID: c3272b570708
Revises: cbebaffd6ea9
Create Date: 2025-12-08 07:19:01.577854

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3272b570708"
down_revision: Union[str, Sequence[str], None] = "cbebaffd6ea9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ExpertUpdateRequests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("expert_vk_id", sa.BigInteger(), nullable=False),
        sa.Column("new_data", sa.JSON(), nullable=False),
        sa.Column("status", sa.Enum("pending", "approved", "rejected"), nullable=True),
        sa.Column("admin_comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["expert_vk_id"], ["ExpertProfiles.user_vk_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ExpertUpdateRequests")
    # ### end Alembic commands ###
