"""change_user_notification_default

Revision ID: cbebaffd6ea9
Revises: d4e84c24a665
Create Date: 2025-11-08 08:45:08.064318

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "cbebaffd6ea9"
down_revision: Union[str, Sequence[str], None] = "d4e84c24a665"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
