"""Add is_private to Event

Revision ID: d2fe54f7ba15
Revises: e37cad1715c2
Create Date: 2025-10-05 22:52:44.574441

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2fe54f7ba15"
down_revision: Union[str, Sequence[str], None] = "e37cad1715c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Events", sa.Column("is_private", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Events", "is_private")
    # ### end Alembic commands ###
