"""g

Revision ID: d4e84c24a665
Revises: a3e3adbcc7e2
Create Date: 2025-11-07 19:06:23.023026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4e84c24a665"
down_revision: Union[str, Sequence[str], None] = "a3e3adbcc7e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Events", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("Events", sa.Column("wall_post_id", sa.Integer(), nullable=True))
    op.drop_index(op.f("promo_word"), table_name="Events")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("promo_word"), "Events", ["promo_word"], unique=True)
    op.drop_column("Events", "wall_post_id")
    op.drop_column("Events", "description")
    # ### end Alembic commands ###
