"""Update promo codes

Revision ID: e0976fa06e9d
Revises: ad4b1c2d3e4f
Create Date: 2026-02-24 14:14:45.728306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0976fa06e9d'
down_revision: Union[str, Sequence[str], None] = 'ad4b1c2d3e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_activations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('activated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['promo_id'], ['promo_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('promo_codes', sa.Column('tariff_id', sa.Integer(), nullable=False))
    op.add_column('promo_codes', sa.Column('activations_limit', sa.Integer(), nullable=True))
    op.add_column('promo_codes', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('promo_codes', 'code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'promo_codes', 'tariffs', ['tariff_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promo_codes', type_='foreignkey')
    op.alter_column('promo_codes', 'code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('promo_codes', 'created_at')
    op.drop_column('promo_codes', 'activations_limit')
    op.drop_column('promo_codes', 'tariff_id')
    op.drop_table('promo_activations')
    # ### end Alembic commands ###
